const employees = [
  {
    id: 1,
    firstName: "Aarav",
    email: "employee1@example.com",
    password: "12345",
    tasks: [
      {
        taskNumber: 1,
        taskTitle: "Prepare Daily Report",
        taskDescription: "Compile and submit the daily productivity report.",
        taskDate: "2025-12-05",
        category: "Reporting",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskNumber: 2,
        taskTitle: "Client Follow-up",
        taskDescription: "Send follow-up emails to pending client queries.",
        taskDate: "2025-12-06",
        category: "Communication",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskNumber: 3,
        taskTitle: "Team Meeting",
        taskDescription: "Attend the weekly team performance meeting.",
        taskDate: "2025-12-07",
        category: "Meetings",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
    ],
    taskStats: {
      active: 0,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
  },

  {
    id: 2,
    firstName: "Ishaan",
    email: "employee2@example.com",
    password: "12345",
    tasks: [
      {
        taskNumber: 1,
        taskTitle: "Update Task Board",
        taskDescription: "Move completed tasks to the finished column.",
        taskDate: "2025-12-05",
        category: "Management",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskNumber: 2,
        taskTitle: "Fix UI Bugs",
        taskDescription: "Resolve minor UI issues reported yesterday.",
        taskDate: "2025-12-06",
        category: "Development",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskNumber: 3,
        taskTitle: "Code Review",
        taskDescription: "Review merge requests from teammates.",
        taskDate: "2025-12-08",
        category: "Development",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskNumber: 4,
        taskTitle: "Testing Module A",
        taskDescription: "Perform manual testing for module A.",
        taskDate: "2025-12-09",
        category: "Testing",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
    ],
    taskStats: {
      active: 1,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
  },

  {
    id: 3,
    firstName: "Vihaan",
    email: "employee3@example.com",
    password: "12345",
    tasks: [
      {
        taskNumber: 1,
        taskTitle: "Data Cleanup",
        taskDescription: "Remove duplicate entries from database.",
        taskDate: "2025-12-04",
        category: "Database",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskNumber: 2,
        taskTitle: "Backup Files",
        taskDescription: "Create a weekly backup for all project files.",
        taskDate: "2025-12-05",
        category: "Maintenance",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskNumber: 3,
        taskTitle: "Security Audit",
        taskDescription: "Perform internal security checks.",
        taskDate: "2025-12-06",
        category: "Security",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
    ],
    taskStats: {
      active: 1,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
  },

  {
    id: 4,
    firstName: "Rohan",
    email: "employee4@example.com",
    password: "12345",
    tasks: [
      {
        taskNumber: 1,
        taskTitle: "Inventory Check",
        taskDescription: "Verify stock levels for all items.",
        taskDate: "2025-12-03",
        category: "Inventory",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskNumber: 2,
        taskTitle: "Vendor Meeting",
        taskDescription: "Discuss pricing updates with vendors.",
        taskDate: "2025-12-06",
        category: "Management",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        taskNumber: 3,
        taskTitle: "Prepare Presentation",
        taskDescription: "Create a presentation for the monthly review.",
        taskDate: "2025-12-10",
        category: "Reporting",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskNumber: 4,
        taskTitle: "Update Documentation",
        taskDescription: "Add new sections to internal documentation.",
        taskDate: "2025-12-11",
        category: "Documentation",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskNumber: 5,
        taskTitle: "Team Training",
        taskDescription: "Attend soft skills training.",
        taskDate: "2025-12-12",
        category: "Training",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
    taskStats: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
  },

  {
    id: 5,
    firstName: "Pritam",
    email: "employee5@example.com",
    password: "12345",
    tasks: [
      {
        taskNumber: 1,
        taskTitle: "Social Media Updates",
        taskDescription: "Post weekly content on social media platforms.",
        taskDate: "2025-12-04",
        category: "Marketing",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        taskNumber: 2,
        taskTitle: "Graphic Design",
        taskDescription: "Create banners for website promotions.",
        taskDate: "2025-12-05",
        category: "Design",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        taskNumber: 3,
        taskTitle: "Campaign Analysis",
        taskDescription: "Analyze the recent marketing campaign performance.",
        taskDate: "2025-12-06",
        category: "Analytics",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        taskNumber: 4,
        taskTitle: "Product Research",
        taskDescription: "Study competitor products for improvements.",
        taskDate: "2025-12-08",
        category: "Research",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
    taskStats: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
  },
];

const admin = [
  {
    id: 1,
    firstName: "Daksh",
    email: "admin@example.com",
    password: "12345",
  },
];

export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};

export const getLocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin"));

  return { employees, admin };
};
